info:
  build:
    description: "@project.description@"
    name: "@project.name@"
    version: "@project.version@"

graylog:
  username: "admin"
  password: "admin"
  configFile: "./graylog/graylog.conf"

spring:
  data:
    elasticsearch:
      clusterName: "graylog"
      properties:
        node:
          local: false
          data: true
        http:
          enabled: true